### ISSUE TITLE
Got wrong message for oh.orthofinder_orthogroups2matrix.pl

### ISSUE THREAD

**Issue by JiaZhong28** [isaisg/gfobap#1]
when i tried to run the script : perl  oh.orthofinder_orthogroups2matrix.pl   faa_folder Orthogroups.txt prefix, I got STDOUT like:
Use of uninitialized value $genome in hash element at oh.orthofinder_orthogroups2matrix.pl line 68, <OR> line 1.
And the output file matrix_raw_orthogroups_.tsv nothing else number but 0.
Is there anyone can help me?

**Comment by isaisg** [comment]
Can you provide more context  about the issue? Over which dataset are you running the script? Which are the inputs that you are providing to the script?

**Comment by JiaZhong28** [comment]
> Can you provide more context about the issue? Over which dataset are you running the script? Which are the inputs that you are providing to the script?

Thanks for replying. For test the pipline, I chose 9 .faa files (each 3 samples were in a group) as the input for orthofinder to  find orthogruops and orthologs, and then the output file Orthogroups.txt were used as the input for  oh.orthofinder_orthogroups2matrix.pl to obtain the matrix. The question is that i'm not sure the obtained matrix_raw_orthogroups_.tsv, which had nothing else number but 0, is due to the warining message i got while running the script, nor the database I used.
The Orthogroups.txt I got looks like this:
>head Orthogroups.txt
OG0000000: BLBNCNDL_00362 BLBNCNDL_00406 BLBNCNDL_00508 BLBNCNDL_00652 BLBNCNDL_00956 BLBNCNDL_00974 BLBNCNDL_01365 BLBNCNDL_01383 BLBNCNDL_01602 BLBNCNDL_01659 BLBNCNDL_01856 BLBNCNDL_02004 BLBNCNDL_02023 BLBNCNDL_02655 BLBNCNDL_02675 EFADNAII_01703 FOABGOGA_00719 MPKECACK_00442 MPKECACK_00804 MPKECACK_00917 MPKECACK_01619 OHNNGIKB_00704 OHNNGIKB_00763 OHNNGIKB_00900 OHNNGIKB_00979 OHNNGIKB_01246 OHNNGIKB_01476 OHNNGIKB_01518 OHNNGIKB_01532 OHNNGIKB_01573 OHNNGIKB_01951 OHNNGIKB_02003 OHNNGIKB_02059 OHNNGIKB_02103 OHNNGIKB_02510
And the  script for oh.orthofinder_orthogroups2matrix.pl  were:
> perl oh.orthofinder_orthogroups2matrix.pl <path to .faa file for orthofinder> Orthogroups.txt  prefix 
The STDOUT were like:
head rename.e
Use of uninitialized value $genome in hash element at /orthofinder_orthogroups_to_matrices/oh.orthofinder_orthogroups2matrix.pl line 68, <OR> line 1.
Use of uninitialized value $genome in hash element at /orthofinder_orthogroups_to_matrices/oh.orthofinder_orthogroups2matrix.pl line 68, <OR> line 1.
Use of uninitialized value $genome in hash element at /orthofinder_orthogroups_to_matrices/oh.orthofinder_orthogroups2matrix.pl line 68, <OR> line 1.
Use of uninitialized value $genome in hash element at /orthofinder_orthogroups_to_matrices/oh.orthofinder_orthogroups2matrix.pl line 68, <OR> line 1.

**Comment by isaisg** [comment]
Are you passing the following parameters?
<path to .faa files>
<prefix>
The original call of the script is 
perl oh.orthofinder_orthogroups2matrix.pl <path to .faa file for orthofinder> Orthogroups.txt <prefix>
Call the script as perl oh.orthofinder_orthogroups2matrix.p and then as first parameter pass the path were you have the original faa files. The second parameter you need to pass is the Orthogroups.txt file and finally a third parameter that is a prefix to append to the output matrix file.
