### ISSUE TITLE
some problemes on enrichment.

### ISSUE THREAD

**Issue by JiaZhong28** [isaisg/gfobap#2]
hi,
I met some problemes about the "enrichment test" module.

1.  In the "README" file:
"In the test_enrichments file we have the pangenome matrix matrix_Xanthomonadaceae_cog.tsv . As well, in the same folder we have the metadata file available at and the phylogenetic tree available at.

To compute all the enrichments we simply call the wrapper:

oh.wrapper_enrichment.sh matrix_Xanthomonadaceae_cog.tsv"

I wonder what does matrix_Xanthomonadaceae_cog.tsv file look like, and how to get this file?

2.  In your article,the annotation by using "COG/KO/TIGRFAM/Pfam" does not have the detailed description.
I would be appreciated if you give us more  information about this ,such as your script or parameters.
And how to convert the annotation results to the matrix which are used for the five test methods.
3. How should I get the "calculation of phylogentic diversity results"?
Look forward to your reply.
Yangfan Liu

**Comment by isaisg** [comment]
Hello Yangfan,
I added the files needed to run  the test wrapper oh.wrapper_enrichment.sh
The files are: metadata_file metadata_3837_genomes_june2016_complete.tsv
Phylogenetic tree: 3837_genomes_31scg_june2016.newick
and Matrix matrix_raw_orthogroups_Xanthomonadaceae.tsv
Please be aware that you need to have R installed with the following R libraries for the wrapper to work properly
library(ape)
library(phytools)
library(bugwas)
library(ape)
library(phylolm)
As well you will need scoary installed.Finally remember to modify this line in the oh.wrapper_enrichment.sh 
#Modify the spath  to wherever the enrichment scripts are located
#e.g spath=/path/example/

Finally just a reminder that there is a dedicated site where we deposited the results of the models and all the files needed to re-run the analyses.
http://labs.bio.unc.edu/Dangl/Resources/gfobap_website/index.html
Isai
